name: Windows docker
on:
  push

jobs:
  download-plugin:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        unreal: ['4.27', '5.3']

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4        
        with:
          path: checkout

      # Once Windows Docker images become available at Sentry's GitHub package registry we'll handle build/tests same as in ci.yml 
      - name: Setup Sentry Unreal sample
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://github.com/getsentry/sentry-unreal/releases/download/0.22.0/sentry-unreal-0.22.0-engine${{ matrix.unreal }}-github.zip" -OutFile "sentry-plugin.zip"
          New-Item -ItemType Directory -Path "${{ github.workspace }}\checkout\sample\Plugins\sentry" -Force
          Expand-Archive -Path "sentry-plugin.zip" -DestinationPath "${{ github.workspace }}\checkout\sample\Plugins\sentry" -Force

      - name: Run Docker stuff
        run: |
          echo ${{ secrets.DOCKER_TOKEN }} | docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker run -td `
            --name unreal `
            --volume "${{ github.workspace }}:C:\workspace" `
            --workdir C:\workspace `
            ghcr.io/tustanivsky/ue-docker-test:${{ matrix.unreal }}
          docker exec unreal C:\UnrealEngine\Engine\Build\BatchFiles\RunUAT.bat BuildCookRun `
            -project=C:\workspace\checkout\sample\SentryPlayground.uproject `
            -archivedirectory=C:\workspace\checkout\sample\Builds `
            -platform=Win64 `
            -nop4 `
            -cook `
            -build `
            -stage `
            -prereqss `
            -package `
            -archive
          docker exec unreal C:\UnrealEngine\Engine\Binaries\Win64\UE4Editor.exe C:\workspace\checkout\sample\SentryPlayground.uproject `
            -ReportExportPath=C:\workspace\checkout\sample\Saved\Automation `
            -ExecCmds="Automation RunTests Sentry;quit" `
            -TestExit="Automation Test Queue Empty" `
            -Unattended `
            -NoPause `
            -NoSplash `
            -NullRHI
